name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run run:smoke
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-artifacts
          path: cypress/reports/html
          retention-days: 30
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        if: always()
        with:
          name: cypress-artifacts
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Automation
          SLACK_TITLE: Regression Test
          SLACK_MESSAGE: "Test Automation Report :rocket:\nhttps://github.com/Guna98/AutomationSlack/actions/runs/${{github.run_id}}"
          SLACK_ATTACHMENTS: '[{"fallback": "Cypress Video", "text": "Cypress Execution Video", "video_url": "https://github.com/Guna98/AutomationSlack/cypress/videos/${{ steps.download-artifact.outputs.artifact_path }}"}]'
          SLACK_ICON_EMOJI: ':smiley:'
          SLACK_COLOR: ${{ job.status }}
          
        
          
          