name: Cypress Tests
 
on: [push]
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6 # use the explicit version number
        with:
          command: npm run smoke
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-video
          path: cypress/videos
          retention-days: 30
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Automation
          SLACK_TITLE: "Regression Test"
          SLACK_MESSAGE: "Test Automation Report :rocket:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ":robot_face:"
          SLACK_ATTACHMENTS: '[{"color": "' + '${{ job.status }}' + '", "title": "Cypress Test Results", "text": "All tests passed! :tada:", "footer": "Automated Test", "ts": ' + '${{ github.event.head_commit.timestamp }}' + '}]'