name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6 # use the explicit version number
        with:
          command: npm run run:smoke
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-video
          path: cypress/videos
          retention-days: 30
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        if: always()
        with:
          name: cypress-execution-video
      - name: Set video file name
        id: set-video-name
        run: echo "VIDEO_FILE_NAME=Login.cy.js.mp4" >> $GITHUB_ENV # Update this to dynamically set the video file name
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Automation
          SLACK_TITLE: Regression Test
          SLACK_MESSAGE: "Test Automation Report :rocket:\nhttps://github.com/Guna98/AutomationSlack/actions/runs/${{github.run_id}}"
          SLACK_ATTACHMENTS: '[{"fallback": "Cypress Video", "text": "Cypress Execution Video", "video_url": "/home/runner/work/AutomationSlack/AutomationSlack/cypress/videos/${{ env.VIDEO_FILE_NAME }}", "title": "View Video", "title_link": "/home/runner/work/AutomationSlack/AutomationSlack/cypress/videos/${{ env.VIDEO_FILE_NAME }}"}]'
          SLACK_ICON_EMOJI: ':smiley:'
          SLACK_COLOR: ${{ job.status }}
          
        
          
          